import {
  apiKeys,
  attendance,
  attendanceTypes,
  attendanceXAttendanceTypes,
  authAccounts,
  authSessions,
  authVerificationTokens,
  auth_emailMfaCodes,
  auth_oauthAccessTokens,
  auth_oauthAuthorizationCodes,
  auth_oauthClients,
  auth_oauthRefreshTokens,
  eventInstances,
  eventInstancesXEventTypes,
  events,
  eventsXEventTypes,
  eventTags,
  eventTagsXEvents,
  eventTagsXEventInstances,
  eventTypes,
  locations,
  orgs,
  orgsXSlackSpaces,
  permissions,
  positions,
  positionsXOrgsXUsers,
  roles,
  rolesXApiKeysXOrg,
  rolesXPermissions,
  rolesXUsersXOrg,
  slackSpaces,
  slackUsers,
  updateRequests,
  users,
} from "../drizzle/schema";

/** Public schema tables */
export const schema = {
  attendance,
  attendanceTypes,
  attendanceXAttendanceTypes,
  apiKeys,
  authAccounts,
  authSessions,
  authVerificationTokens,
  events,
  eventInstances,
  eventInstancesXEventTypes,
  eventTags,
  eventTagsXEvents,
  eventTagsXEventInstances,
  eventTypes,
  eventsXEventTypes,
  locations,
  orgs,
  permissions,
  positions,
  positionsXOrgsXUsers,
  roles,
  rolesXApiKeysXOrg,
  rolesXPermissions,
  rolesXUsersXOrg,
  slackSpaces,
  slackUsers,
  orgsXSlackSpaces,
  updateRequests,
  users,
};

/** Auth schema tables (auth.*) — kept separate to avoid name collisions */
export const authSchema = {
  emailMfaCodes: auth_emailMfaCodes,
  oauthAccessTokens: auth_oauthAccessTokens,
  oauthAuthorizationCodes: auth_oauthAuthorizationCodes,
  oauthClients: auth_oauthClients,
  oauthRefreshTokens: auth_oauthRefreshTokens,
};

export * from "drizzle-orm";
