import {
  apiKeys,
  attendance,
  attendanceTypes,
  attendanceXAttendanceTypes,
  authAccounts,
  authSessions,
  authVerificationTokens,
  emailMfaCodes,
  eventInstances,
  eventInstancesXEventTypes,
  events,
  eventsXEventTypes,
  eventTags,
  eventTagsXEvents,
  eventTagsXEventInstances,
  eventTypes,
  locations,
  oauthAccessTokens,
  oauthAuthorizationCodes,
  oauthClients,
  oauthRefreshTokens,
  orgs,
  orgsXSlackSpaces,
  permissions,
  positions,
  positionsXOrgsXUsers,
  roles,
  rolesXApiKeysXOrg,
  rolesXPermissions,
  rolesXUsersXOrg,
  slackSpaces,
  slackUsers,
  updateRequests,
  users,
} from "../drizzle/schema";

export const schema = {
  attendance,
  attendanceTypes,
  attendanceXAttendanceTypes,
  apiKeys,
  authAccounts,
  authSessions,
  authVerificationTokens,
  events,
  eventInstances,
  eventInstancesXEventTypes,
  eventTags,
  eventTagsXEvents,
  eventTagsXEventInstances,
  eventTypes,
  eventsXEventTypes,
  locations,
  orgs,
  permissions,
  positions,
  positionsXOrgsXUsers,
  roles,
  rolesXApiKeysXOrg,
  rolesXPermissions,
  rolesXUsersXOrg,
  slackSpaces,
  slackUsers,
  orgsXSlackSpaces,
  updateRequests,
  users,
};

/** Auth schema tables (auth.*) — kept separate to avoid name collisions */
export const authSchema = {
  emailMfaCodes,
  oauthAccessTokens,
  oauthAuthorizationCodes,
  oauthClients,
  oauthRefreshTokens,
};

export * from "drizzle-orm";
