import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";

import { SubmitBugReportCard } from "~/app/help/submit-bug-report-card";

const { mutateAsync, toast } = vi.hoisted(() => ({
  mutateAsync: vi.fn(),
  toast: { success: vi.fn(), error: vi.fn() },
}));

vi.mock("@acme/ui/toast", () => ({ toast }));

vi.mock("~/orpc/react", () => ({
  useMutation: () => ({ mutateAsync }),
  orpc: { map: { submitFeedback: { mutationOptions: () => ({}) } } },
}));

// The Subject label's `for` and the Input's `id` are generated by separate
// `useId()` calls and don't match, so `getByLabelText` can't find it here;
// the placeholder is the only reliable selector for this field.
const subjectInput = () =>
  screen.getByPlaceholderText("I have feedback about ...");

const fillAndSubmit = (subject: string) => {
  fireEvent.change(subjectInput(), { target: { value: subject } });
  fireEvent.click(screen.getByRole("button", { name: "Submit" }));
};

describe("SubmitBugReportCard", () => {
  beforeEach(() => {
    mutateAsync.mockReset();
    toast.success.mockReset();
    toast.error.mockReset();
  });

  it("clears the form after a successful submit", async () => {
    mutateAsync.mockResolvedValue(undefined);
    render(<SubmitBugReportCard />);

    fillAndSubmit("Found a bug");

    await waitFor(() => expect(toast.success).toHaveBeenCalled());
    expect(subjectInput()).toHaveValue("");
  });

  it("shows an error toast and keeps the draft when the submission fails", async () => {
    mutateAsync.mockRejectedValue(new Error("network error"));
    render(<SubmitBugReportCard />);

    fillAndSubmit("Found a bug");

    await waitFor(() => expect(toast.error).toHaveBeenCalled());
    expect(subjectInput()).toHaveValue("Found a bug");
    expect(toast.success).not.toHaveBeenCalled();
  });

  it("alerts and skips the mutation when the subject exceeds the schema's length cap", async () => {
    const alertSpy = vi.spyOn(window, "alert").mockImplementation(() => void 0);
    render(<SubmitBugReportCard />);

    fillAndSubmit("x".repeat(201));

    await waitFor(() => expect(alertSpy).toHaveBeenCalledWith("form error"));
    expect(mutateAsync).not.toHaveBeenCalled();

    alertSpy.mockRestore();
  });

  it("does not erase a draft typed while the first submission was still in flight", async () => {
    let resolveSubmit!: () => void;
    mutateAsync.mockReturnValue(
      new Promise<void>((resolve) => {
        resolveSubmit = resolve;
      }),
    );
    render(<SubmitBugReportCard />);

    fillAndSubmit("Original subject");

    // Wait for the submission to actually start before changing the draft.
    // Validation runs asynchronously, so changing the input right after the
    // click could land before `onSubmit` captures its `values` snapshot --
    // that snapshot would then already read "New draft" too, and the guard
    // this test exercises would never actually see values diverge.
    await waitFor(() => expect(mutateAsync).toHaveBeenCalled());

    // The visitor starts a new message before the first submit resolves.
    fireEvent.change(subjectInput(), {
      target: { value: "New draft" },
    });

    resolveSubmit();
    await waitFor(() => expect(toast.success).toHaveBeenCalled());
    expect(subjectInput()).toHaveValue("New draft");
  });
});
