-- R5 bootstrap migration (hand-written): Postgres roles, GRANTs, and
-- append-only REVOKEs on region_custom_domain_events.
--
-- Source of truth: docs/plans/2026-04-14-multi-tenant-saas-refactor.md,
-- Decision 8 "Layer 2 — Neon Postgres roles and GRANTs".
--
-- This file is NOT auto-generated by drizzle-kit. It lives in sql/ (not
-- drizzle/) because Drizzle does not model roles/grants/triggers. Apply
-- AFTER the drizzle migration (0000_*.sql) has created the tables.
--
-- BEFORE APPLYING: replace every CHANGE_ME_BEFORE_APPLY password with the
-- real secret from Secret Manager. Each role gets its own connection
-- string stored in its own Secret Manager secret, accessed only by the
-- service that needs it. Do NOT commit real passwords to this file.

-- Bootstrap migration, run once against the f3-redirect-platform Neon project.

-- ========================================================================
-- Runtime role: read-only, minimum column set.
-- ========================================================================
CREATE ROLE redirect_runtime LOGIN PASSWORD 'CHANGE_ME_BEFORE_APPLY';
GRANT CONNECT ON DATABASE platform TO redirect_runtime;
GRANT USAGE ON SCHEMA public TO redirect_runtime;
GRANT SELECT (id, hostname, region_slug, region_id, lifecycle_state)
  ON region_custom_domains TO redirect_runtime;
-- Runtime sees NOTHING else. No org_region_bindings, no events, no quota.

-- ========================================================================
-- Reconciler role: read/write on domain tables. Append-only on events.
-- ========================================================================
CREATE ROLE redirect_reconciler LOGIN PASSWORD 'CHANGE_ME_BEFORE_APPLY';
GRANT CONNECT ON DATABASE platform TO redirect_reconciler;
GRANT USAGE ON SCHEMA public TO redirect_reconciler;
GRANT SELECT, INSERT, UPDATE ON region_custom_domains TO redirect_reconciler;
GRANT SELECT ON org_region_bindings TO redirect_reconciler;
GRANT SELECT, INSERT, UPDATE, DELETE ON reconciler_leases TO redirect_reconciler;
-- Append-only events (R5):
GRANT SELECT, INSERT ON region_custom_domain_events TO redirect_reconciler;
REVOKE UPDATE, DELETE, TRUNCATE ON region_custom_domain_events FROM redirect_reconciler;
-- Reconciler cannot modify bindings, cannot touch quota.

-- ========================================================================
-- Admin UI role: read/write on domains and bindings. Append-only on events.
-- ========================================================================
CREATE ROLE redirect_admin_ui LOGIN PASSWORD 'CHANGE_ME_BEFORE_APPLY';
GRANT CONNECT ON DATABASE platform TO redirect_admin_ui;
GRANT USAGE ON SCHEMA public TO redirect_admin_ui;
GRANT SELECT, INSERT, UPDATE ON region_custom_domains TO redirect_admin_ui;
GRANT SELECT, INSERT, UPDATE ON org_region_bindings TO redirect_admin_ui;
GRANT SELECT ON domain_blocklist TO redirect_admin_ui;
GRANT SELECT, INSERT, UPDATE ON org_domain_quota TO redirect_admin_ui;
-- Append-only events (R5):
GRANT SELECT, INSERT ON region_custom_domain_events TO redirect_admin_ui;
REVOKE UPDATE, DELETE, TRUNCATE ON region_custom_domain_events FROM redirect_admin_ui;

-- ========================================================================
-- Platform admin role: used ONLY by migrations. Not held by any runtime service.
-- ========================================================================
CREATE ROLE redirect_platform_admin LOGIN PASSWORD 'CHANGE_ME_BEFORE_APPLY';
GRANT ALL PRIVILEGES ON DATABASE platform TO redirect_platform_admin;
-- Only this role can ALTER TABLE, create triggers, rotate secrets, etc.
-- Its connection string is in a fourth Secret Manager secret accessed only
-- by the CI migration job, not by any Cloud Run service in the hot path.
