import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";

import RootLayout, { metadata } from "./layout";

vi.mock("next/font/google", () => ({
  Geist: () => ({ variable: "font-geist" }),
  Geist_Mono: () => ({ variable: "font-geist-mono" }),
}));

describe("RootLayout", () => {
  it("exports the default metadata", () => {
    expect(metadata).toEqual({
      title: "Create Next App",
      description: "Generated by create next app",
    });
  });

  it("wraps children with the expected html and body classes", () => {
    const html = renderToStaticMarkup(
      <RootLayout>
        <div>content</div>
      </RootLayout>,
    );

    expect(html).toContain('lang="en"');
    expect(html).toContain("font-geist");
    expect(html).toContain("font-geist-mono");
    expect(html).toContain("<div>content</div>");
  });
});
