name: Recreate staging branch

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  recreate-staging:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'staging'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: main
          fetch-depth: 0
      - name: Recreate staging branch from main
        run: |
          git push origin main:staging --force
